---
- name: Copy 'is_cluster_ready' file
  copy: dest=/bin/is_cluster_ready src=is_cluster_ready mode=0755

- set_fact: kube_pod_network_cidr='192.168.0.0/16'
  when: kube_network == 'calico'

- name: force handlers
  meta: flush_handlers

- name: Kubeadm init
  command: kubeadm init --pod-network-cidr={{kube_pod_network_cidr}} --token={{kube_token}} --token-ttl {{kube_token_ttl}} --apiserver-advertise-address={{kube_api_server}} creates=/etc/kubernetes/admin.conf

- name: wait Kube to start
  wait_for: port=6443

- lineinfile:
    dest: /etc/sysctl.d/k8s.conf
    regexp: '^net.bridge.bridge-nf-call-iptables'
    line: 'net.bridge.bridge-nf-call-iptables = 1'
    create: yes
  notify: sysctl-system
  when: kube_network == 'flannel' or kube_network == 'kube-router' or kube_network == 'romana'

- block:
    - template: src=flannel-net.j2 dest=/tmp/flannel-net.yml
    - command: kubectl apply -f /tmp/flannel-net.yml creates=/etc/cni/net.d/10-flannel.conflist
      environment:
        KUBECONFIG: /etc/kubernetes/admin.conf
  when: kube_network == 'flannel'

- block:
    - copy: src=calico-net.yaml dest=/tmp/calico-net.yaml
    - command: kubectl apply -f /tmp/calico-net.yaml creates=/var/etcd/calico-data
      environment:
        KUBECONFIG: /etc/kubernetes/admin.conf
  when: kube_network == 'calico'

- block:
    - copy: src=romana-net.yml dest=/tmp/romana-net.yml
    - command: kubectl apply -f /tmp/romana-net.yml creates=/var/lib/romana/etcd-db
      environment:
        KUBECONFIG: /etc/kubernetes/admin.conf
  when: kube_network == 'romana'

- block:
    - copy: src=kuberouter-net.yaml dest=/tmp/kuberouter-net.yaml
    - command: kubectl apply -f /tmp/kuberouter-net.yaml creates=/etc/cni/net.d/10-kuberouter.conf
      environment:
        KUBECONFIG: /etc/kubernetes/admin.conf
  when: kube_network == 'kube-router'

- block:
    - copy: src=weave-net.yaml dest=/tmp/weave-net.yaml
    - command: kubectl apply -f /tmp/weave-net.yaml creates=/etc/cni/net.d/10-weave.conf
      environment:
        KUBECONFIG: /etc/kubernetes/admin.conf
  when: kube_network == 'weave'

- include: helm.yaml
  environment:
    KUBECONFIG: /etc/kubernetes/admin.conf
  when: kube_install_helm

- block:
    - copy: src=kubernetes-dashboard.yaml dest=/tmp/kubernetes-dashboard.yaml
    - command: kubectl apply -f /tmp/kubernetes-dashboard.yaml
      environment:
        KUBECONFIG: /etc/kubernetes/admin.conf
  when: kube_deploy_dashboard

- block:
    - copy: src=metrics-server.yaml dest=/tmp/metrics-server.yaml
    - command: kubectl apply -f /tmp/metrics-server.yaml
      environment:
        KUBECONFIG: /etc/kubernetes/admin.conf
  when: kube_install_metrics

- name: Add persistent volumes to kube cluster
  block:
    - template: src=persistent-volumes.j2 dest=/tmp/kubernetes-persistent-volumes.yml
    - command: kubectl apply -f /tmp/kubernetes-persistent-volumes.yml
      environment:
        KUBECONFIG: /etc/kubernetes/admin.conf
  when: kube_persistent_volumes != []

- name: Install Git package
  package: name=git
  when: kube_apply_repos != []

- name: Download git repo "{{ item.repo }}"
  git:
    repo: "{{ item.repo }}"
    dest: "/tmp/{{ item.repo | basename }}"
    version: "{{ item.version }}"
  with_items: "{{ kube_apply_repos }}"

- name: apply path "{{ item.path }}"
  command: kubectl apply -f "{{ item.path }}" chdir="/tmp/{{ item.repo | basename }}"
  environment:
    KUBECONFIG: /etc/kubernetes/admin.conf
  with_items: "{{ kube_apply_repos }}"

- name: Add Kube API server options
  lineinfile:
    dest: /etc/kubernetes/manifests/kube-apiserver.yaml
    line: '    - {{item.option}}={{item.value}}'
    regexp: '^    - {{item.option}}='
    insertafter: '    - kube-apiserver'
  notify: restart kubeapi
  with_items: "{{ kube_apiserver_options }}"

- copy:
    dest: /etc/profile.d/kube.sh
    content: "export KUBECONFIG=/etc/kubernetes/admin.conf"

- name: force handlers
  meta: flush_handlers

- block:
    - copy: src=ingress-nginx.yaml dest=/tmp/ingress-nginx.yaml
    - command: kubectl apply -f /tmp/ingress-nginx.yaml
      environment:
        KUBECONFIG: /etc/kubernetes/admin.conf
  when: kube_install_ingress

- block:
    - copy: src=nvidia-device-plugin.yml dest=/tmp/nvidia-device-plugin.yml
    - command: kubectl apply -f /tmp/nvidia-device-plugin.yml
      environment:
        KUBECONFIG: /etc/kubernetes/admin.conf
  when: kube_nvidia_support

- block:
    - copy: src=kubernetes-dashboard-ingress.yaml dest=/tmp/kubernetes-dashboard-ingress.yaml
    - command: kubectl apply -f /tmp/kubernetes-dashboard-ingress.yaml
      environment:
        KUBECONFIG: /etc/kubernetes/admin.conf
  when: kube_install_ingress and kube_deploy_dashboard

- name: Install NFS Server
  apt: name=nfs-kernel-server state=present force=yes
  when: ansible_distribution == "Ubuntu" and kube_install_nfs_server == "yes"

- block:
    - name: Copy exports config file for NFS Server
    - copy:
        src: exports
        dest: /etc/exports
        owner: root
        group: root
        mode: '0644'

    - name: Create dirs for current export file
    - file:
        path: /export/data
        state: directory
        owner: nobody
        group: nogroup
        mode: '0777'

    - name: Restart nfs-server
        service:
        name: nfs-kernel-server
        state: restarted

  when: ansible_distribution == "Ubuntu" and kube_install_nfs_server == "yes" and kube_nfs_server_exports == "yes"

- include: kubeapps.yaml
  when: kube_install_kubeapps
